name: Jobs / Pre-Build
on:
        workflow_call:
                # inputs:
                #   lockfile-hash:
                #     description: 'node_modules cache hash key.'
                #     type: string
                #     required: true

jobs:
        pre-build:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v4

                        - uses: pnpm/action-setup@v2
                          name: Install pnpm
                          with:
                            version: 8
                            run_install: false
                        
                        - uses: actions/setup-node@v4
                          with:
                            node-version: '18'
                            cache: 'pnpm'
                        - run: pnpm install 

                        - name: Run Format
                          run: pnpm format

                        # - name: Run Lint
                        #   run: yarn lint

                        # - name: Run Test
                        #   run: npm run test

                        # - name: Generate Test Reporter
                        #   run: npm run test:reporter
