name: Jobs / Pre-Build
on:
        workflow_call:
                # inputs:
                #   lockfile-hash:
                #     description: 'node_modules cache hash key.'
                #     type: string
                #     required: true

jobs:
        pre-build:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v4

                        - name: Compute dependency
                          id: compute_lockfile_hash_key
                          run: echo "hash=${{ hashFiles('**/yarn.lock') }}" >> $GITHUB_OUTPUT

                        - name: Cache node_modules
                          id: cache-node-modules
                          uses: actions/cache@v2
                          with:
                                  path: node_modules
                                  key: ${{ steps.compute_lockfile_hash_key.outputs.hash }}

                        - name: Install dependencies
                          if: steps.cache-node-modules.outputs.cache-hit != 'true'
                          run: npm ci

                        - name: Run Format
                          run: npm run format

                        - name: Run Lint
                          run: npm run lint

                        # - name: Run Test
                        #   run: npm run test

                        # - name: Generate Test Reporter
                        #   run: npm run test:reporter
